[project]
title = "Structured Labs Online Assessment"
version = "0.1.0"
port = 8501
slug = "my-project-553897"  
entrypoint = "hello.py"    

[branding]
name = "Google Daily News"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.Google_Daily_News_csv]
type = "csv"
path = "data/Google_Daily_News_.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"